#1 Install and config Nginx
- name: import an official nginx signing key
  apt_key: 
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Import Nginx Official Repo
  apt_repository:
    repo: deb [arch=amd64] http://nginx.org/packages/ubuntu {{ansible_distribution_release}} nginx
    filename: nginx
    update_cache: yes

- name: Install Nginx
  apt:
    name: [nginx]

#2 Install Certbot for Nginx
- name: Install certbot
  shell: |
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository universe
    echo "" | add-apt-repository ppa:certbot/certbot 
    apt-get update
    apt-get install -y certbot python3-certbot-nginx
    certbot renew --dry-run
  when: nginx_certbot

- name: Change Directory Owner
  file:
    path: /data/{{item}}
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - wwwroot
    - cert
