- block:
  - name: Import Nginx Official stable Repo
    yum_repository:
      name: nginx-stable-repo
      description: nginx stable repo
      file: nginx-stable
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://nginx.org/keys/nginx_signing.key

  - name: Import Nginx Official mainline Repo
    yum_repository:
      name: nginx-mainline-repo
      description: nginx mainline repo
      file: nginx-mainline
      baseurl: http://nginx.org/packages/mainline/centos/$releasever/$basearch/
      gpgcheck: yes
      enabled: no
      gpgkey: https://nginx.org/keys/nginx_signing.key
  when: ansible_distribution == 'CentOS'

- block:
  - name: Import Nginx Official stable Repo
    yum_repository:
      name: nginx-stable-repo
      description: nginx stable repo
      file: nginx-stable
      baseurl: http://nginx.org/packages/centos/7/$basearch/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://nginx.org/keys/nginx_signing.key

  - name: Import Nginx Official mainline Repo
    yum_repository:
      name: nginx-mainline-repo
      description: nginx mainline repo
      file: nginx-mainline
      baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
      gpgcheck: yes
      enabled: no
      gpgkey: https://nginx.org/keys/nginx_signing.key
  when: ansible_distribution == 'Amazon'

- name: Install Nginx
  yum:
    name: [nginx]

#2 Install Certbot for Nginx
- name: Install certbot
  shell: |
    yum install -y certbot python2-certbot-nginx
    echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null
  when: nginx_certbot
  
- name: Change Directory Owner
  file:
    path: /data/{{item}}
    state: directory
    owner: nginx
    group: nginx
  with_items:
    - wwwroot
    - cert
